version: 2.1
jobs:
  build:
    docker: 
      - image: ubuntu:18.04
    steps:
      - checkout # check out the code in the project directory
      - run: echo $DOTENV | base64 --decode > .env
      - run: apt-get update && apt-get install -y make wget jq redis-tools
      - run: ./test/test.sh
      - run: make wget
      - run: make grep
      - run: make aggregate

